# Generated by Django 4.2 on 2023-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0002_alter_news_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='html_content',
            field=models.TextField(max_length=5000),
        ),
    ]
