# Generated by Django 4.2 on 2023-04-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulb', '0007_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='main_img_url',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulb.tags'),
        ),
    ]
